// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0qhT_8sCKpy3WRbUGJ3LfSZL7gIoSqgk',
    appId: '1:254357801662:web:c1913fdaae58d0c1e66cef',
    messagingSenderId: '254357801662',
    projectId: 'todo-app-e25ee',
    authDomain: 'todo-app-e25ee.firebaseapp.com',
    storageBucket: 'todo-app-e25ee.firebasestorage.app',
    measurementId: 'G-SERL6WFFKS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3s4l9SzNbPoHDpR27NIO5ymr3Ll6pvcQ',
    appId: '1:254357801662:android:b752c37ab95c6351e66cef',
    messagingSenderId: '254357801662',
    projectId: 'todo-app-e25ee',
    storageBucket: 'todo-app-e25ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB66yHzWeLOQAaqyFo5jrFbYsBWDw47NyY',
    appId: '1:254357801662:ios:21f5862cefece6dbe66cef',
    messagingSenderId: '254357801662',
    projectId: 'todo-app-e25ee',
    storageBucket: 'todo-app-e25ee.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB66yHzWeLOQAaqyFo5jrFbYsBWDw47NyY',
    appId: '1:254357801662:ios:21f5862cefece6dbe66cef',
    messagingSenderId: '254357801662',
    projectId: 'todo-app-e25ee',
    storageBucket: 'todo-app-e25ee.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVceYqHlstDH943nbaC7DMiR4hYYZI8bA',
    appId: '1:254357801662:web:f9626b26a38e9e8ae66cef',
    messagingSenderId: '254357801662',
    projectId: 'todo-app-e25ee',
    authDomain: 'todo-app-e25ee.firebaseapp.com',
    storageBucket: 'todo-app-e25ee.firebasestorage.app',
    measurementId: 'G-S01MWTGWW9',
  );

}